=== AIRobo18/C-Programming/Lab1_4/task1/catalog.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="semester" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="season" type="xs:string"/>
              <xs:element name="year" type="xs:float"/>
              <xs:element name="major" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="course" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="programName" type="xs:string"/>
                          <xs:element name="courseName" type="xs:string"/>
                          <xs:element name="courseNumber" type="xs:string"/>
                          <xs:element name="unitWeight" type="xs:string"/>
                          <xs:element name="description" type="xs:string"/>
                          <xs:element name="instructor" type="xs:string"/>
                          <xs:element name="time" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AIRobo18/C-Programming/Lab1_4/task2/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="catalog.xsd">
  <semester>
    <season> FALL </season>
    <year> 2016 </year>
    <major>
      <course>
        <programName> COMP </programName>
        <courseName> Programming Languages </courseName>
        <courseNumber> 232 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> Discussion of issues in the design, implementation, and use of high-level programming languages. Topics include: historical background; how languages reflect different design philosophies and user requirements; technical issues in the design of major imperative (procedural) programming languages; other approaches to programming: functional programming, logic programming, and object-oriented programming. </description>
        <instructor> Andrzej Bieszczad </instructor>
        <time> M 2:00pm - 3:50pm, W 3:00pm - 5:50pm </time>
      </course>
      <course>
        <programName> COMP </programName>
        <courseName> Computer Organization and Architecture </courseName>
        <courseNumber> 262 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> Extension of basic addressing concepts to more advanced addressability such as base register and self relative addressing. Topics include: comparative computer architecture focusing on such organizations as multiple register processors and stack machines; basics of virtual memory, input/output; introduction to the concept of  microprogrammable systems; low-level language translation process associated with assemblers; system functions such as relocatable loading and memory management; application of data structure and hashing techniques to the above. </description>
        <instructor> Leo Benegas </instructor>
        <time> T 4:00pm - 5:50pm, Th 3:00pm - 5:50pm </time>
      </course>
      <course>
        <programName> COMP </programName>
        <courseName> Data Structures And Programming Design </courseName>
        <courseNumber> 151 </courseNumber>
        <unitWeight> 4 </unitWeight>
        <description> Introduction to data structures and the algorithms that use them. Review of composite data types such as arrays, records, strings, and sets. Topics include: the role of the abstract data type in program design, definition, implementation and application of data structures such as stacks, queues, linked lists, trees and graphs recursion use of time-complexity expressions in evaluating algorithms. comparative study of sorting and searching algorithms. </description>
        <instructor> Anna Bieszczad </instructor>
        <time> MW 12:00pm - 1:50pm </time>
      </course>
      <course>
        <programName> COMP </programName>
        <courseName> Computer Architecture and Assembly Language </courseName>
        <courseNumber> 162 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> An introduction to computer architecture, assembly language programming, system software and computer applications. Topics include: number systems and data representation internal organization of a computer primitive instructions and operations Assembly language language translation principles overview of operating systems. </description>
        <instructor> Peter Smith </instructor>
        <time> W 12:00pm - 1:50pm, F 10:00am - 12:50pm </time>
      </course>
      <course>
        <programName> COMP </programName>
        <courseName> Object-Oriented Programming </courseName>
        <courseNumber> 150 </courseNumber>
        <unitWeight> 4 </unitWeight>
        <description> Course taught in a lab. Introduction to algorithms, their representation, design, structuring, analysis and optimization. The course introduces the concept of object paradigm, design and implementation of algorithms as structured programs in a high level language. </description>
        <instructor> Anna Bieszczad </instructor>
        <time> TTh 12:00 - 1:50pm </time>
      </course>
    </major>
    <major>
      <course>
        <programName> MATH </programName>
        <courseName> Calculus I </courseName>
        <courseNumber> 150 </courseNumber>
        <unitWeight> 4 </unitWeight>
        <description> A course in analytic geometry and calculus. Topics include: elementary and transcendental functions, their properties, limits, derivatives, integrals and mathematical modeling. </description>
        <instructor> Robert Ream </instructor>
        <time> MW 8:00am - 9:50am </time>
      </course>
      <course>
        <programName> MATH </programName>
        <courseName> Calculus II </courseName>
        <courseNumber> 151 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> Topics include: differentiation, integration, sequences, infinite series, and power series. </description>
        <instructor> Selenne Banuelos </instructor>
        <time> TTh 10:00am - 11:50am </time>
      </course>
      <course>
        <programName> MATH </programName>
        <courseName> Calculus III </courseName>
        <courseNumber> 250 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> Topics include: functions of several variables, solid analytic geometry, partial differentiation, multiple integrals with applications; vector analysis, and line and surface integrals. </description>
        <instructor> Cindy Wyels </instructor>
        <time> TTh 9:00am - 10:15am </time>
      </course>
      <course>
        <programName> MATH </programName>
        <courseName> Logic and Mathematical Reasoning </courseName>
        <courseNumber> 230 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> Introduction to deductive logic, logical and critical thinking, and symbolic approaches to common language. Includes abstract sets and number sets, relations, propositional logic, and the theory of quantification. </description>
        <instructor> Dennis Slivinski </instructor>
        <time> TTh 1:30pm - 2:45pm </time>
      </course>
      <course>
        <programName> MATH </programName>
        <courseName> Linear Algebra </courseName>
        <courseNumber> 240 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> Topics include: matrices, linear systems of equations, determinants, vectors in 2 and 3 dimensions, eigenvalues, the vector space Rn , linear transformations, introduction to general vector spaces and applications. </description>
        <instructor> Selenne Banuelos </instructor>
        <time> TTh 1:30pm - 2:45pm </time>
      </course>
    </major>
    <major>
      <course>
        <programName> BIOL </programName>
        <courseName> Life in the Universe </courseName>
        <courseNumber> 110 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> Explains the origins of life on Earth and the conditions for life to be discovered on other worlds. Current and potential means of exploring space will be discussed such as: Mars rovers, radio telescopes and the promise and limitations of interstellar travel. </description>
        <instructor> Clinton Harper </instructor>
        <time> TTh 3:00pm - 4:15pm </time>
      </course>
      <course>
        <programName> BIOL </programName>
        <courseName> Cell and Molecular Biology </courseName>
        <courseNumber> 201 </courseNumber>
        <unitWeight> 4 </unitWeight>
        <description> This course will cover principles of basic chemistry, biological macromolecules, prokaryotic and eukaryotic cell structure and function, homeostasis, metabolism including both respiration and photosynthesis, cell division, signal transduction, Mendelian genetics, molecular genetics including transcription and translation, and a brief introduction to virology and immunology. The philosophy of science, scientific method and experimental design are foundational to the course. </description>
        <instructor> Jessica Dalton </instructor>
        <time> TTh 12:00pm - 2:50pm </time>
      </course>
      <course>
        <programName> BIOL </programName>
        <courseName> Neurobiology and Cognitive Sci </courseName>
        <courseNumber> 212 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> Principles of brain organization and function underlying behavior. Topics include neuroanatomy and physiology of language, vision, sexual behavior, memory and abnormal behavior. </description>
        <instructor> Charles Sackerson </instructor>
        <time> MW 3:00pm- 4:15pm </time>
      </course>
      <course>
        <programName> BIOL </programName>
        <courseName> Sex, Germs and Diseases </courseName>
        <courseNumber> 213 </courseNumber>
        <unitWeight> 3 </unitWeight>
        <description> This is a course to introduce biology of sexually transmitted diseases and their impact on society. It covers reproductive system, factors in the spread of diseases, biology and pathogenesis of infectious agents and sexually transmitted diseases caused by bacteria, viruses, fungi and protozoa. Topics also include impact of current biotechnology in relation to vaccine development, treatment and improved diagnostics of these diseases as well as challenges of these diseases to economy, public health system, individuals, and society at large. </description>
        <instructor> Patricia Tavormina </instructor>
        <time> W 12:00pm - 2:50pm </time>
      </course>
      <course>
        <programName> BIOL </programName>
        <courseName> Microbiology </courseName>
        <courseNumber> 301 </courseNumber>
        <unitWeight> 4 </unitWeight>
        <description> An introduction to the structure, function and diversity of microorganisms. Explores topics including microbial identification, diversity, metabolism, pathology, microbial ecology, and the role of microbes in human society. </description>
        <instructor> Erich Fleming </instructor>
